[project]
name = "gundi-client-v2"
dynamic = ["version"]
description = "An async client for Gundi's API"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
authors = [
    { name = "Chris Doehring", email = "chrisdo@earthranger.com" },
    { name = "Mariano M", email = "marianom@earthranger.com" },
    { name = "Victor Garcia", email = "victorg@earthranger.com" },
]

dependencies = [
    "environs>=9.5,<12",
    "pydantic>=1.10,<2",
    "httpx>=0.24,<1.0",
    "gundi-core>=1.5.8,<3",
]

[dependency-groups]
dev = [
    "respx>=0.22",
    "black>=23.1",
    "pytest>=7.2",
    "pytest-asyncio>=0.20",
]

[tool.hatch.version]
path = "gundi_client_v2/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
